- name: download Composer
  shell: creates="composer.phar" chdir="/tmp" curl -s http://getcomposer.org/installer | php

- name: install Composer globally
  shell: creates="/usr/local/bin/composer" chdir="/tmp"  mv composer.phar /usr/local/bin/composer
  
- name: install Composer Asset Plugin
  shell: "composer global require 'fxp/composer-asset-plugin:1.0.0-beta4'"