---
- name: add PostgreSQL repository signing key
  shell: sudo wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

- name: add PostgreSQL repo
  shell: echo 'deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main' | sudo tee /etc/apt/sources.list.d/pgdg.list

- name: install PostgreSQL
  apt: pkg=postgresql-9.3 state=latest update_cache=yes
  notify: restart postgresql

