# - name: run wx project composer
  # shell: cd /var/www/wechat-app-advanced && composer install --prefer-dist && composer update --prefer-dist
 
# - name: set Init run permissions
#   file: path=/var/www/wechat-app-advanced/init mode=0744
#   notify:
#     - restart nginx

# - name: init project
#   shell: yes | /var/www/wechat-app-advanced/init --env=Development

# - name: set Local config with correct MySQL connection etc. (2 steps to fix Windows shared folder error)
#   template: src={{item}} dest=/tmp/{{item}}
#   with_items:
#    - common-main-local.php
#    - frontend-main-local.php
#    - backend-main-local.php

# - name: set Local config with correct MySQL connection etc. (2 steps to fix Windows shared folder error)
#   command: mv /tmp/{{item.src}} {{item.dest}}
#   with_items:
#    - { src: 'common-main-local.php', dest: '/var/www/wechat-app-advanced/common/config/main-local.php' }
#    - { src: 'frontend-main-local.php', dest: '/var/www/wechat-app-advanced/frontend/config/main-local.php' }
#    - { src: 'backend-main-local.php', dest: '/var/www/wechat-app-advanced/backend/config/main-local.php' }
